<?php

namespace Municipios\MuniBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MuniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuniRepository extends EntityRepository
{
}
